#!/bin/bash
# OceanBase Inventory Generator Script
# This script generates Ansible inventory from Terraform outputs

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
TERRAFORM_DIR="$REPO_ROOT/terraform/oceanbase"
INVENTORY_FILE="$REPO_ROOT/ansible/inventory/oceanbase_hosts"

echo "=== OceanBase Inventory Generator ==="
echo ""

# Check if we're in the right directory
if [ ! -d "$TERRAFORM_DIR" ]; then
    echo "Error: Terraform directory not found: $TERRAFORM_DIR"
    exit 1
fi

# Navigate to terraform directory
cd "$TERRAFORM_DIR"

# Check if terraform state exists
if [ ! -f "terraform.tfstate" ]; then
    echo "Error: terraform.tfstate not found. Please run 'terraform apply' first."
    exit 1
fi

echo "Extracting OceanBase VM information from Terraform state..."
echo ""

# Get observer private IPs
OBSERVER_IPS=$(terraform output -json observer_private_ips 2>/dev/null | jq -r '.[]' || echo "")
if [ -z "$OBSERVER_IPS" ]; then
    echo "Warning: Could not extract observer IPs from terraform state"
    OBSERVER_IPS=""
fi

# Get observer VM names
OBSERVER_NAMES=$(terraform output -json observer_vm_names 2>/dev/null | jq -r '.[]' || echo "")
if [ -z "$OBSERVER_NAMES" ]; then
    echo "Warning: Could not extract observer names from terraform state"
    OBSERVER_NAMES=""
fi

# Get cluster name
CLUSTER_NAME=$(terraform output -raw oceanbase_cluster_name 2>/dev/null || echo "ob_cluster")
ROOT_PASSWORD=$(terraform output -raw oceanbase_root_password 2>/dev/null || echo "OceanBase#!123")
MEMORY_LIMIT=$(terraform output -raw oceanbase_memory_limit 2>/dev/null || echo "8G")
CPU_COUNT=$(terraform output -raw oceanbase_cpu_count 2>/dev/null || echo "8")

# Count observers
INSTANCE_COUNT=$(echo "$OBSERVER_IPS" | grep -c . || echo "0")

echo "Found $INSTANCE_COUNT observer nodes"
echo ""

# Generate inventory file
cat > "$INVENTORY_FILE" << EOF
# OceanBase Cluster Inventory
# Auto-generated by $(basename "$0") on $(date)
# DO NOT EDIT MANUALLY - Re-run this script to regenerate

[oceanbase]
EOF

# Add observer nodes
if [ -n "$OBSERVER_IPS" ] && [ -n "$OBSERVER_NAMES" ]; then
    mapfile -t IPS_ARRAY <<< "$OBSERVER_IPS"
    mapfile -t NAMES_ARRAY <<< "$OBSERVER_NAMES"
    
    for i in "${!IPS_ARRAY[@]}"; do
        IP="${IPS_ARRAY[$i]}"
        NAME="${NAMES_ARRAY[$i]:-ob-observer-$i}"
        echo "$NAME ansible_host=$IP private_ip=$IP" >> "$INVENTORY_FILE"
    done
else
    echo "# No observer nodes found in terraform state" >> "$INVENTORY_FILE"
fi

# Add variables section
cat >> "$INVENTORY_FILE" << EOF

[oceanbase:vars]
ansible_user=oceanadmin
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
oceanbase_cluster_name=$CLUSTER_NAME
oceanbase_root_password=$ROOT_PASSWORD
oceanbase_memory_limit=$MEMORY_LIMIT
oceanbase_cpu_count=$CPU_COUNT
oceanbase_mysql_port=2881
oceanbase_rpc_port=2882
oceanbase_obshell_port=2886
EOF

echo "✓ Inventory file generated: $INVENTORY_FILE"
echo ""
echo "=== Inventory Preview ==="
cat "$INVENTORY_FILE"
echo ""
echo "========================="
echo ""
echo "Next steps:"
echo "1. Review and update SSH key path in inventory if needed"
echo "2. Run: cd $REPO_ROOT/ansible"
echo "3. Run: source ~/ansible-venv/bin/activate  (if using virtualenv)"
echo "4. Run: ansible-playbook -i inventory/oceanbase_hosts playbooks/deploy_oceanbase_cluster.yml"
