#!/bin/bash
set -uo pipefail

MYSQL="mysql -h172.17.1.7 -P2881 -uroot@sys -pOceanBase#!123 -Doceanbase -A"

echo "=== SERVER RESOURCES ==="
$MYSQL -e "SELECT SVR_IP, CPU_CAPACITY, CPU_ASSIGNED, MEM_CAPACITY, MEM_ASSIGNED FROM GV\$OB_SERVERS"

echo ""
echo "=== TENANTS ==="
$MYSQL -e "SELECT TENANT_ID, TENANT_NAME, MIN_CPU, MAX_CPU, MEMORY_SIZE FROM DBA_OB_TENANTS"

echo ""
echo "=== TOP WAIT EVENTS ==="
$MYSQL -e "SELECT EVENT, TOTAL_WAITS, TIME_WAITED_MICRO FROM GV\$SYSTEM_EVENT WHERE TOTAL_WAITS > 100 ORDER BY TIME_WAITED_MICRO DESC LIMIT 20"

echo ""
echo "=== UNIT CONFIG ==="
$MYSQL -e "SELECT UNIT_CONFIG_ID, NAME, MAX_CPU, MIN_CPU, MEMORY_SIZE, LOG_DISK_SIZE, MAX_IOPS, MIN_IOPS FROM DBA_OB_UNIT_CONFIGS"

echo ""
echo "=== RESOURCE POOLS ==="
$MYSQL -e "SELECT RESOURCE_POOL_ID, NAME, UNIT_COUNT, UNIT_CONFIG_ID, TENANT_ID FROM DBA_OB_RESOURCE_POOLS"

echo ""
echo "=== DISK IO STATS ==="  
$MYSQL -e "SELECT SVR_IP, DISK_TYPE, TOTAL_SIZE, FREE_SIZE FROM GV\$OB_DISK_STAT" 2>/dev/null || echo "(view not available)"

echo ""
echo "=== MEMSTORE INFO ==="
$MYSQL -e "SELECT SVR_IP, TENANT_ID, ACTIVE_MEMSTORE_USED, TOTAL_MEMSTORE_USED, MEMSTORE_LIMIT FROM GV\$OB_MEMSTORE" 2>/dev/null || echo "(view not available)"

echo ""
echo "=== MERGE HISTORY (last 10) ==="
$MYSQL -e "SELECT SVR_IP, LS_ID, TABLET_ID, TYPE, START_TIME, FINISH_TIME FROM GV\$OB_TABLET_COMPACTION_HISTORY ORDER BY START_TIME DESC LIMIT 10" 2>/dev/null || echo "(view not available)"

echo ""
echo "=== CLOG DISK USAGE ==="
$MYSQL -e "SELECT SVR_IP, SVR_PORT, TOTAL_SIZE, IN_USE_SIZE FROM GV\$OB_LOG_STAT WHERE TENANT_ID=1 LIMIT 3" 2>/dev/null || echo "(view not available)"
