---
# Default variables for OceanBase role

oceanbase_cluster_name: "ob_cluster"
oceanbase_root_password: "OceanBase#!123"
oceanbase_memory_limit: "8G"
oceanbase_cpu_count: 8
oceanbase_data_disk_size_gb: 500
oceanbase_redo_disk_size_gb: 200
oceanbase_mysql_port: 2881
oceanbase_rpc_port: 2882
oceanbase_obshell_port: 2886
oceanbase_all_in_one_url: "https://github.com/oceanbase/oceanbase/releases/download/v4.3.5.0/oceanbase-all-in-one-4.3.5_bp4_20250910.el8.x86_64.tar.gz"
oceanbase_data_mount_device: "/dev/mapper/vgob-lvob"
oceanbase_strict_mount_check: true

# Deployment paths
oceanbase_home_dir: /home/admin/oceanbase
oceanbase_data_dir: /oceanbase/data
oceanbase_redo_dir: /oceanbase/redo
oceanbase_server_dir: /oceanbase/server

# System configuration
oceanbase_admin_user: admin
oceanbase_admin_group: admin
oceanbase_ssh_port: 22
